<?php 
    require 'templates/header.phtml';
    require 'templates/form_subida.phtml'; 
?>

<ul class="list-group">
<?php foreach($individuos as $individuo) : ?>
    <li class="list-group-item item-task">
        <div>
            <h5><b>Nombre: <?= $individuo->nombre ?></b></h5> 
            <h6>Especie: <?= $individuo->especie ?></h6>
            <h6>Color: <?= $individuo->color ?></h6>
            <h6>Edad (años): <?= $individuo->edad ?></h6>
        </div>
        <div class="actions">
            <a href="mostrar/<?= $individuo->id?>" type="button" class='btn btn-success ml-auto'>Ver mas</a> 
            <a href="eliminar/<?= $individuo->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a> 
            <a href="mostrarParaModificar/<?= $individuo->id ?>" type="button" class='btn btn-secondary ml-auto'>Modificar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/footer.phtml'; ?>